version: '2'

services:
  redis:
    container_name: nqm_redis
    image: redis:4.0
    restart: always
    volumes:
      - ./docker/data/redis:/data

  node:
    hostname: api
    container_name: nqm_node
    image: node:8.9
    user: node
    working_dir: /home/node/nqm
    environment:
      - NODE_ENV=development
    restart: always
    links:
      - redis
    volumes:
      - ./:/home/node/nqm
    command: "yarn test"
